// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestarRapsodya.Data;

#nullable disable

namespace RestarRapsodya.Migrations
{
    [DbContext(typeof(RestarRapsodyaContext))]
    partial class RestarRapsodyaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestarRapsodya.Models.Estado", b =>
                {
                    b.Property<int>("id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Estado"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id_Estado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Mesa", b =>
                {
                    b.Property<int>("id_Mesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Mesa"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("id_Estado")
                        .HasColumnType("int");

                    b.HasKey("id_Mesa");

                    b.HasIndex("id_Estado");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Pedido", b =>
                {
                    b.Property<int>("id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Pedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Correo_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nombre_Plato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fecha_Pedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_Mesa")
                        .HasColumnType("int");

                    b.HasKey("id_Pedido");

                    b.HasIndex("Correo_Usuario");

                    b.HasIndex("id_Mesa");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Rol", b =>
                {
                    b.Property<int>("id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Rol"));

                    b.Property<string>("nombre_Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_Rol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Usuario", b =>
                {
                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Correo");

                    b.HasIndex("id_Rol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Mesa", b =>
                {
                    b.HasOne("RestarRapsodya.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("id_Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Pedido", b =>
                {
                    b.HasOne("RestarRapsodya.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Correo_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestarRapsodya.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("id_Mesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestarRapsodya.Models.Usuario", b =>
                {
                    b.HasOne("RestarRapsodya.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
